### ISSUE TITLE
Test and data 

### ISSUE THREAD

**Issue by shani1610** [xyxingx/Point-Cloud-Color-Constancy#2]
Hello, 
A few questions and notes: 

- is it possible to use the test and not the train? how? 
- where should the data be located in the hierarchy? and what should it contain?
- the PointNetFeat class is missing, I used the one from here: https://github.com/fxia22/pointnet.pytorch/blob/master/pointnet/model.py
- please note that the datasetloader in train_main should be dataloader. 

Thank you

**Comment by xyxingx** [comment]
Hi, Thanks for pointing out the typo and the misaligned problem. We've updated the files.

- In terms of data,  it is an N x 6 numpy array. In particular, [:,:3] is the point coordinate [x,y,z], [:,3:] is the color value [r,g,b].

- In terms of testing, we are using 3-fold cross-validation, you can directly test it fold by fold. The fold information can be found in the .csv files from [here](https://drive.google.com/drive/folders/1qBw_bvaxIvduIm2vzrYhEPX9khTm1Bo9). 

Cheers,

**Comment by namnh-tut** [comment]
@xyxingx Hi, the 79th line inside the 'dataloader.py' file is as follows:
`pcd = pcd.transpose(1,0)`
It causes an error: `ValueError: axes don't match array`
Could you confirm this line and also the whole file of  'dataloader.py' whether include any typo or un-updated part?
We could not run the code smoothly.

**Comment by xyxingx** [comment]
@namnh-tut Hi,

I confirm there should not be any typo in this file. Could you check the shape of data?

**Comment by shani1610** [comment]
Hello, 
I have the sizes mismatch issues as @namnh-tut . 
I've set the required environment and I'm trying to run the repo without any changes to the data you've provided, with the default arguments, which in this case it's the ETH3 dataset. 

**label_path** directs to the file **ETH3_folds.csv**

**self.gt_path** directs to the dir **/ETH3d/labels/**  (labels dir contain .npy files) 

**self.data_path** directs to the files **/ETH3d/pcd_** (this directory is taken from PointCloud dir from the data you provided, divided into pcd_16 and pcd_64 directories, each contains .npy as well)

meaning the image directory in the data you've provided is not in use. 

pls, correct me if I'm doing something wrong. 
I'll appreciate any help.

**Comment by xyxingx** [comment]
@shani1610 Hi, If you use the right path of data, it should run smoothly. 
If you load the point cloud data in the right way, the shape of the point cloud should be _(n,6)_, where n is the number of points. I can't see any problem from my side.

The image files in the image directory are raw images (converted from the original *.NEF or *.DNG file). I provide the images for evaluating the visual results (in full resolution). And you can also use them to generate the different scales of point clouds. 

Again, could you make sure:

1. the data is loaded correctly (right path/files name). 
2. if the shape of the point cloud matches _(n,6)_ (I will suggest printing the shape of `pcd` before line 79)

If the **data is loaded correctly and the shape of the point cloud matches**. I think the problem will be solved. 
If the problem still exists, put your code here, and I would be glad to help.

**Comment by namnh-tut** [comment]
@xyxingx Thank you for your response. We tried to do as the instruction and the code could run but we faced a new problem:

```
start train.....
Traceback (most recent call last):
  File "train_main.py", line 97, in <module>
	pred,_ = network(img)
  File "/home/xxxxxxxx/anaconda3/envs/DLenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
	result = self.forward(*input, **kwargs)
  File "./pointnet/model.py", line 231, in forward
	x, trans = self.feat(x)
  File "/home/xxxxxxxx/anaconda3/envs/DLenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
	result = self.forward(*input, **kwargs)
  File "./pointnet/model.py", line 188, in forward
	trans = self.stn(x)
  File "/home/xxxxxxxx/anaconda3/envs/DLenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
	result = self.forward(*input, **kwargs)
  File "./pointnet/model.py", line 71, in forward
	x = F.relu(self.bn1(self.conv1(x)))
  File "/home/xxxxxxxx/anaconda3/envs/DLenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
	result = self.forward(*input, **kwargs)
  File "/home/xxxxxxxx/anaconda3/envs/DLenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 200, in forward
	self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

We tried to search for this on the Internet and tried a lot of methods but still cannot get it to work.
Do you have any idea about this?

**Comment by xyxingx** [comment]
Hi there, the CUDA error is out of my control, so I can not provide any solution. I will close the issue since there is nothing to do with my repo.
